website/auth.py
from flask import Blueprint, render_template, redirect, url_for, request, flash
from . import db
from .models import User
from flask_login import login_user, login_required, logout_user, current_user
from werkzeug.security import generate_password_hash , check_password_hash


auth = Blueprint("auth", __name__)

@auth.route("/login", methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get("email")
        password = request.form.get("password")

        user = User.query.filter_by(email=email).first()
        
        if user:

            if check_password_hash(user.password, password):
                flash("Logged in!", category="success")
                login_user(user, remember=True)
                return redirect(url_for("views.home"))

            else:
                flash("Password is incorrect.", category="erorr")

        else:   
              flash("Email does not exits.", category="erorr")    

    return render_template("login1.html", user=current_user)

@auth.route("/sing-up", methods=['GET', 'POST'])
def singup():
    if request.method == 'POST':
        username = request.form.get("username")
        email = request.form.get("email")
        password1 = request.form.get("password1")
        password2 = request.form.get("password2")

        email_exists =  User.query.filter_by(email=email).first()
        username_exists = User.query.filter_by(username=username).first()

        if email_exists:
            flash("Email already in use.", category='erorr')

        elif username_exists:
            flash("This Username already exists.", category='erorr')

        elif password1 != password2:
            flash("password don\'t match!", category='erorr')

        elif len(username) < 2:
            flash("Username is too short!", category="erorr")

        elif len(password1) < 6:
            flash("Password is too short!", category='erorr')

        elif len(email) < 4:
            flash("Email is too short!", category='erorr')

        else:
            new_user = User(username=username, email=email, password=generate_password_hash(password1, method='sha256'))
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user, remember=True)
            flash("User created!")
            return redirect(url_for('views.home'))


    return render_template("singup.html", user=current_user)

@auth.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("views.home"))

website/templates/about.html
{% extends "base.html" %} {% block title %}About Us{% endblock %}
<!--block link bray link kardan file css!-->>
{% block link%}{% endblock %}
{% block content %}
<br>
<br>
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
  <link rel="stylesheet" href="{{ url_for('static', filename='js/home.js') }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='styles/home.css') }}">
</head>
<body>
    <br><br><br><br>
    <div class="w3-display-left w3-text-white" style="padding:48px"></div>
    <h1 class="w3-jumbo w3-hide-small">A social network for programmers</h1>
    <h1 class="w3-xxlarge w3-hide-large w3-hide-medium">A social network</h1>
    <H3 class="w3-large">With free registration, you can enter the community of programmers and start your activity :)</H3>
    <div class="w3-display-bottomleft w3-text-grey w3-large" style="padding:24px 48px">
        <i class="fa fa-facebook-official w3-hover-opacity"></i>
        <i class="fa fa-instagram w3-hover-opacity"></i>
        <i class="fa fa-snapchat w3-hover-opacity"></i>
        <i class="fa fa-pinterest-p w3-hover-opacity"></i>
        <i class="fa fa-twitter w3-hover-opacity"></i>
        <i class="fa fa-linkedin w3-hover-opacity"></i>
    </div>
    <p><a href="/login" class="w3-button w3-white w3-padding-large w3-large w3-margin-top w3-opacity w3-hover-opacity-off">Learn more and start today</a></p>
</body>
</html>
{% endblock %}

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/b0da5b9f43.js"
    crossorigin="anonymous"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://www.w3schools.com/lib/w3-theme-blue-grey.css">
    <link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Open+Sans'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    {% block link %}{% endblock %}
    <title> {% block title %} {% endblock %}</title>
</head>
<body>
    <nav>
    <div class="w3-top">
        <div class="w3-bar w3-theme-d2 w3-left-align w3-large">
         <a class="w3-bar-item w3-button w3-hide-medium w3-hide-large w3-right w3-padding-large w3-hover-white w3-large w3-theme-d2" href="javascript:void(0);" onclick="openNav()"><i class="fa fa-bars"></i></a>
         <a href="/about" class="w3-bar-item w3-button w3-padding-large w3-theme-d4"><i class="fa fa-home w3-margin-right"></i>social network</a>
         <a href="/home" class="w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white" title="Posts"><i class="fa fa-globe"></i></a>
         {% if user.is_authenticated %}
         <a href="/create-post" class="w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white" title="create-post"><i class="fas fa-plus"></i></a>
         <a href="/logout" class="w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white" title="Logout"><i class="fas fa-sign-out-alt"></i></a>
         <div class="w3-dropdown-hover w3-hide-small">
         </div>
         <a href="/profile/{{ user.id }}" class="w3-bar-item w3-button w3-hide-small w3-right w3-padding-large w3-hover-white" title="My Account">
           <img src="https://www.w3schools.com/w3images/avatar2.png" class="w3-circle" style="height:23px;width:23px" alt="Avatar">
         </a>
         {% else %}
         <a href="/login" class="w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white" title="Login"><i class="fas fa-user-alt"></i></a>
         <a href="/sing-up" class="w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white" title="Sing Up"><i class="fas fa-user-plus"></i></a>
         {% endif %}
        </div>
       </div>
    </nav>

       
       <!-- Navbar on small screens -->
       <div id="navDemo" class="w3-bar-block w3-theme-d2 w3-hide w3-hide-large w3-hide-medium w3-large">
         <a href="#" class="w3-bar-item w3-button w3-padding-large">Link 1</a>
         <a href="#" class="w3-bar-item w3-button w3-padding-large">Link 2</a>
         <a href="#" class="w3-bar-item w3-button w3-padding-large">Link 3</a>
         <a href="#" class="w3-bar-item w3-button w3-padding-large">My Profile</a>
       </div>
    {% with messages = get_flashed_messages(with_categories=True) %}
        {% if messages %}
            {% for categori, message in messages %}
            {% if categori == "erorr" %}
                <br>
                <br>
                <div class="alert alert-danger alert-dismissible  fade show" role="alert">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
                </div>
            {% else %}
                <br>
                <br>
                <div class="alert alert-success alert-dismissible  fade show" role="alert">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
                </div>
            {% endif %}
            {% endfor %}
        {% endif %}
    {% endwith %}
   <div class="container">
    {% block content %} {% endblock %}
   </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/index.js') }}"></script>
</body>
</html>

website/templates/create_post.html
{% extends "base.html" %} {% block title %}Create Post{% endblock %}


{% block content %}
<link rel="stylesheet" href="{{ url_for('static', filename='styles/styles.css') }}">
<style>
    input[type=text], select {
    width: 100%;
    padding: 12px 20px;
    margin: 8px 0;
    display: inline-block;
    border: 1px solid #ccc;
    border-radius: 4px;
    box-sizing: border-box;
   }
    button[type=submit] {
        width: 100%;
        background-color: #395B64;
        color: white;
        padding: 14px 20px;
        margin: 8px 0;
        border: none;
        border-radius: 4px;
        cursor: pointer;
    }
</style>
<body>
    <br>
    <br>
    <br>
    <br>
    <h1 align="center">New Post</h1>

    <form method="POST">
        <label for="fname">title: </label><br>
        <input type="text" name="title" id="title" class="form-contorol">
        <br>
        <label for="fname">tweet: </label><br>
        <textarea name="text" id="text" class="form-control"></textarea>
        <br>

        <div align="Right" class="post">
            <button class="btn btn-lg btn-primary" type="submit">Post</button>
        </div>
    </form>
    <br>
    <div align="Left">
        <a href="/home"><button type="button" class="btn btn-secondary btn-lg">Back</button></a>
    </div>
</body>

{% endblock %}

website/templates/home.html
{% extends "posts_div.html" %}
{% block title %}Home{% endblock %}

website/templates/login.html
{% extends "base.html" %} {% block title %}Login{% endblock %}
{% block content %}
<style>
    body {
    background-color: #000960;
    font-size: 1.6rem;
    font-family: "Open Sans", sans-serif;
    color: #2b3e51;
  }

  h2 {
    font-weight: 300;
    text-align: center;
  }

  p {
    position: relative;
  }

  a,
  a:link,
  a:visited,
  a:active {
    color: #0044D7;
    -webkit-transition: all 0.2s ease;
    transition: all 0.2s ease;
  }
  a:focus, a:hover,
  a:link:focus,
  a:link:hover,
  a:visited:focus,
  a:visited:hover,
  a:active:focus,
  a:active:hover {
    color: #329dd5;
    -webkit-transition: all 0.2s ease;
    transition: all 0.2s ease;
  }

  #login-form-wrap {
    background-color: #fff;
    width: 35%;
    margin: 30px auto;
    text-align: center;
    padding: 20px 0 0 0;
    border-radius: 4px;
    box-shadow: 0px 30px 50px 0px rgba(0, 0, 0, 0.2);
  }

  #login-form {
    padding: 0 60px;
  }

  input {
    display: block;
    box-sizing: border-box;
    width: 100%;
    outline: none;
    height: 60px;
    line-height: 60px;
    border-radius: 4px;
  }

  input[type="text"],
  input[type="email"] {
    width: 100%;
    padding: 0 0 0 10px;
    margin: 0;
    color: #8a8b8e;
    border: 1px solid #c2c0ca;
    font-style: normal;
    font-size: 16px;
    -webkit-appearance: none;
       -moz-appearance: none;
            appearance: none;
    position: relative;
    display: inline-block;
    background: none;
  }
  input[type="text"]:focus,
  input[type="email"]:focus {
    border-color: #3ca9e2;
  }
  input[type="text"]:focus:invalid,
  input[type="email"]:focus:invalid {
    color: #cc1e2b;
    border-color: #cc1e2b;
  }
  input[type="text"]:valid ~ .validation,
  input[type="email"]:valid ~ .validation {
    display: block;
    border-color: #0C0;
  }
  input[type="text"]:valid ~ .validation span,
  input[type="email"]:valid ~ .validation span {
    background: #0C0;
    position: absolute;
    border-radius: 6px;
  }
  input[type="text"]:valid ~ .validation span:first-child,
  input[type="email"]:valid ~ .validation span:first-child {
    top: 30px;
    left: 14px;
    width: 20px;
    height: 3px;
    -webkit-transform: rotate(-45deg);
            transform: rotate(-45deg);
  }
  input[type="text"]:valid ~ .validation span:last-child,
  input[type="email"]:valid ~ .validation span:last-child {
    top: 35px;
    left: 8px;
    width: 11px;
    height: 3px;
    -webkit-transform: rotate(45deg);
            transform: rotate(45deg);
  }

  .validation {
    display: none;
    position: absolute;
    content: " ";
    height: 60px;
    width: 30px;
    right: 15px;
    top: 0px;
  }

  input[type="submit"] {
    border: none;
    display: block;
    background-color: #3ca9e2;
    color: #fff;
    font-weight: bold;
    text-transform: uppercase;
    cursor: pointer;
    -webkit-transition: all 0.2s ease;
    transition: all 0.2s ease;
    font-size: 18px;
    position: relative;
    display: inline-block;
    cursor: pointer;
    text-align: center;
  }
  input[type="submit"]:hover {
    background-color: #329dd5;
    -webkit-transition: all 0.2s ease;
    transition: all 0.2s ease;
  }

  #create-account-wrap {
    background-color: #eeedf1;
    color: #8a8b8e;
    font-size: 14px;
    width: 100%;
    padding: 10px 0;
    border-radius: 0 0 4px 4px;
  }
</style>
	<div id="login-form-wrap">
	  <h2>Login</h2>
	  <form id="login-form" method="post">
		<p>
		<input type="text" id="username" name="password" placeholder="Enter password" required>
		<i class="validation"><span></span><span></span></i>
		</p>
		<p>
		<input type="email" id="email" name="email" placeholder="Email Address" required>
		<i class="validation"><span></span><span></span></i>
		</p>
		<p>
		<input type="submit" id="login" value="Login">
		</p>
	  </form>
	  <div id="create-account-wrap">
		<p>Not a member? <a href="#">Create Account</a><p>
	  </div>
	</div>
{% endblock %}

website/templates/login1.html
{% extends "base.html" %} {% block title %}Login{% endblock %}
{% block link %}{% endblock %}
{% block content %}
<head>
	<link rel="stylesheet" href="{{ url_for('static', filename='styles/singup.css') }}">
</head>
<body>
<br>
<br>

	<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<div id="login-form-wrap">
		<h2>Login</h2>
		<form id="login-form" method="post">
			<p>
			<input type="email" id="email" name="email" placeholder="Email Address" required>
			<i class="validation"><span></span><span></span></i>
			</p>
			<p>
			<input type="password" id="username" name="password" placeholder="Enter password" required>
			<i class="validation"><span></span><span></span></i>
			</p>
			<p>
			<input type="submit" id="login" value="Login">
			</p>
		</form>
		<div id="create-account-wrap">
			<p>Not a member? <a href="{{ url_for('auth.singup') }}">Create Account</a><p>
		</div>
		</div>
</body>
{% endblock %}

website/templates/posts.html
{% extends "posts_div.html" %} {% block title %}{{username}}'s Posts {% endblock %}
{% block header %}{{username}}'s Posts{% endblock %} 
{% block footer %}
    <a href="/home"><button type="button" class="btn btn-lg btn-primary">Back</button></a>
{% endblock %}

website/templates/posts_div.html
{% extends "base.html" %} {% block title %}{% endblock %}
{% block content %}
<h1 align="center">{% block header %}Posts</h1>{% endblock %}
<div id="posts">
{% for post in posts %}
<link rel="stylesheet" href="{{ url_for('static', filename='styles/styles.css') }}">
    <div class="card border-dark">
        <div class="card-header d-flex justify-content-between align-iteams-center">

            {% if post.user.image_file %}
                <img src="{{ url_for('static', filename='pictures/' + post.user.image_file) }}" align="left"  class="rounded-circle account-img" width="50">
            {% else %}
                <img src="{{ url_for('static', filename='pictures/profile.jpg') }}" align="left" class="rounded-circle account-img" width="50">
            {% endif %}

            <a href="/posts/{{ post.user.username }}">{{post.user.username}}</a>
            <div class="card-text">{{post.title}}</div>
            <div>
                <span id="likes-count-{{post.id}}">{{ post.likes|length }}</span>

                {% if user.id in post.likes|map(attribute="author")|list %}
                <i class="fas fa-thumbs-up" id="like-button-{{post.id}}" onclick="like({{post.id}})"></i>
                {% else %}
                <i class="far fa-thumbs-up" id="like-button-{{post.id}}" onclick="like({{post.id}})"></i>
                {% endif %}

                {% if user.id == post.author %}
                <div class="btn-group">
                    <button
                    type="button"
                    class="btn btn-sm btn-primary dropdown-toggle"
                    data-bs-toggle="dropdown"></button>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="/delete-post/{{post.id}}" class="dropdown-item">Delete</a>
                        </li>
                    </ul>
                </div>
                {% endif %}
            </div>
        </div>
        <div class="card-body">
            <div class="card-text">{{post.text}}</div>
            <br>
           <div class="collapse" id="comments-{{post.id}}">
                <div class="card">
                    <div class="card-body" id="comments-expanded-{{post.id}}">
                        {% for comment in post.comments %}
                            <div class="d-flex align-items-center justify-content-between">
                                <div>
                                    <a href="/posts/{{comment.user.username}}">{{comment.user.username}}
                                    </a>: {{comment.text}}
                                </div>
                                <div>
                                    <small class="text-muted">{{comment.date_created}}</small>
                                    {% if user.id == comment.author or user.id == post.author %}
                                    <div class="btn-group">
                                        <button
                                        type="button"
                                        class="btn btn-sm btn-primary dropdown-toggle"
                                        data-bs-toggle="dropdown"></button>
                                        <ul class="dropdown-menu">
                                            <li>
                                                <a href="/delete-comment/{{comment.id}}" class="dropdown-item">Delete</a>
                                            </li>
                                        </ul>
                                    </div>
                                    {% endif %}
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
                <br>
           </div>
           <p class="card-text">
            {% if post.comments|length > 0 %}
                    <a data-bs-toggle="collapse" href="#comments-{{post.id}}" role="button">
                        <small>View {{post.comments|length}} Comments</small>
                    </a>
            {% else %}
                    <small class="text-muted">No Comments</small>
            {% endif %}
           </p>

            <form class="mb-3 input-group" method="post" action="/create-comment/{{post.id}}">
                <input type="text" class="form-control" id="text" name="text" placeholder="Comment something" autocomplete="off">
                <button class="btn btn-primary" type="submit">Comment</button>
            </form>
        </div>
        <div class="card-footer text-muted">{{post.date_created}}</div>
    </div>
    <br>
{% endfor %}
{% block footer %}
</div>
    <div align="center">
        <a href="/create-post"><button type="button" class="btn btn-primary btn-lg">
            Create a Post
        </button></a>
    </div>
{% endblock %}
{% endblock %}

website/templates/profile.html
{% extends "base.html" %} {% block title %}Profile{% endblock %}
{% block content %}
<link rel="stylesheet" href="{{ url_for('static', filename='styles/singup.css') }}">

<br>
<br>
<br>
    <div class="content-section">
        <div class="media">
            <img class="rounded-circle account-img" src="{{ image_file }}">
            <div class="media-body">
                <h2 class="account-heading">{{ current_user.username }}</h2>
                <p class="text-secondary">{{ current_user.email }}</p>
            </div>
        </div>
        <h2>Profile</h2> 
        <form enctype="multipart/form-data" method="post" action="/profile/{{ new_user.id }}">
            <p>
            <input type="text" id="username" name="username" value="{{ new_user.username }}" required>
            <i class="validation"><span></span><span></span></i>
            </p>
            <p>
            <input type="email" id="email" name="email" value="{{ new_user.email }}" required>
            <i class="validation"><span></span><span></span></i>
            </p>
            <p>
            <div class="form-group">
                {{ form.profile_pic.label() }}
                {{ form.profile_pic(class="form-control-file") }}
                {% if form.profile_pic.errors %}
                    {% for error in form.profile_pic.errors %}
                        <span class="text-danger">{{ error }}</span> <br>
                    {% endfor %}
                {% endif %}
            </div>
            <button type="submit" class="btn btn-primary btn-m">Submit</button>
            <a href="/home"><button type="button" class="btn btn-secondary btn-m">Cancel</button></a>
            </p>
        </form>
    </div>
{% endblock %}

website/templates/singup.html
{% extends "base.html" %}
{% block title %}Sing Up{% endblock %}
{% block link %}
{% endblock %}
{% block content %}
<head>
	<link rel="stylesheet" href="{{ url_for('static', filename='styles/singup.css') }}">
</head>
<br>
<br>

	<div id="login-form-wrap">
	  <h2>Sing UP</h2>
	  <form id="login-form" method="post">
		<p>
		<input type="text" id="username" name="username" placeholder="Enter Username" required>
		<i class="validation"><span></span><span></span></i>
		</p>
        <p>
        <input type="text" id="email" name="email" placeholder="Enter Email Address" required>
        <i class="validation"><span></span><span></span></i>
        <p>
        <input type="password" id="password1" name="password1" placeholder="Enter password" required>
        <i class="validation"><span></span><span></span></i>
        </p>
        <input type="password" id="password2" name="password2" placeholder="Enter Password Again" required>
        <i class="validation"><span></span><span></span></i>
        </p>
		<p>
		<input type="submit" id="login" value="singup">
		</p>
	  </form>
	  <div id="create-account-wrap">
		<p>Do you have an account?  <a href="/login">login</a><p>
	  </div>
	</div>

{% endblock %}

website/templates/tetest.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://www.w3schools.com/lib/w3-theme-blue-grey.css">
<link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Open+Sans'>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
html, body, h1, h2, h3, h4, h5 {font-family: "Open Sans", sans-serif}
</style>
</head>
<body class="w3-theme-l5">



<!-- Page Container -->
<div class="w3-container w3-content" style="max-width:1400px;margin-top:80px">    
  <!-- The Grid -->
  <div class="w3-row">
    <!-- Left Column -->
    <div class="w3-col m3">
      <!-- Profile -->
      <div class="w3-card w3-round w3-white">
        <div class="w3-container">
         <h4 class="w3-center">My Profile</h4>
         <p class="w3-center"><img src="/w3images/avatar3.png" class="w3-circle" style="height:106px;width:106px" alt="Avatar"></p>
         <hr>
         <p><i class="fa fa-pencil fa-fw w3-margin-right w3-text-theme"></i> name</p>
         <p><i class="fa fa-home fa-fw w3-margin-right w3-text-theme"></i> user</p>
        </div>
      </div>
      <br>
      <br>
      
    <!-- End Left Column -->
    </div>
    
    <!-- Middle Column -->
    <div class="w3-col m7">
    
      <div class="w3-row-padding">
        <div class="w3-col m12">
          <div class="w3-card w3-round w3-white">
            <div class="w3-container w3-padding">
              <h6 class="w3-opacity">new post</h6>
              <p contenteditable="true" class="w3-border w3-padding">post name....</p>
              <p contenteditable="true" class="w3-border w3-padding">post....</p>
              <button type="button" class="w3-button w3-theme"><i class="fa fa-pencil"></i>  Post</button> 
            </div>
          </div>
        </div>
      </div>
      
      <div class="w3-container w3-card w3-white w3-round w3-margin"><br>
        <img src="/w3images/avatar2.png" alt="Avatar" class="w3-left w3-circle w3-margin-right" style="width:60px">
        <span class="w3-right w3-opacity">2022-09-25 16:33:56</span>
        <h4>user name</h4><br>
        <hr class="w3-clear">
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
          <div class="w3-row-padding" style="margin:0 -16px">
        </div>
        <button type="button" class="w3-button w3-theme-d1 w3-margin-bottom"><i class="fa fa-thumbs-up"></i>  Like</button> 
        <button type="button" class="w3-button w3-theme-d2 w3-margin-bottom"><i class="fa fa-comment"></i>  Comment</button> 
      </div>
      

    <!-- End Middle Column -->
    </div>
    
    <!-- Right Column -->
    <div class="w3-col m2">
      <div class="w3-card w3-round w3-white w3-center">
        <div class="w3-container">
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium ipsa odio voluptatibus esse! Nam officiis accusamus autem tenetur saepe veniam ratione iure! Eos, aliquid magnam omnis adipisci tenetur perferendis alias!</p>
        </div>
      </div>
      <br>
      

      </div>

      
    <!-- End Right Column -->
    </div>
    
  <!-- End Grid -->
  </div>
  
<!-- End Page Container -->
</div>
<br>

<!-- Footer -->
<footer class="w3-container w3-theme-d3 w3-padding-16">
  <h5>cs50</h5>
</footer>

<footer class="w3-container w3-theme-d5">
  <p>Powered by <a href="#" target="_blank">cs50x iran</a></p>
</footer>
 
<script>
// Accordion
function myFunction(id) {
  var x = document.getElementById(id);
  if (x.className.indexOf("w3-show") == -1) {
    x.className += " w3-show";
    x.previousElementSibling.className += " w3-theme-d1";
  } else { 
    x.className = x.className.replace("w3-show", "");
    x.previousElementSibling.className = 
    x.previousElementSibling.className.replace(" w3-theme-d1", "");
  }
}

// Used to toggle the menu on smaller screens when clicking on the menu button
function openNav() {
  var x = document.getElementById("navDemo");
  if (x.className.indexOf("w3-show") == -1) {
    x.className += " w3-show";
  } else { 
    x.className = x.className.replace(" w3-show", "");
  }
}
</script>

</body>
</html> 